### ISSUE TITLE
FR: Make bing zoom level configurable

### ISSUE THREAD

**Issue by robmarkcole** [ESA-PhiLab/iris#47]
Currently the zoom level is hard coded [I think here](https://github.com/ESA-PhiLab/iris/blob/b5e07329ecf8d91b3eb4b3d4f05bf5229f657557/iris/static/javascripts/views.js#L450) but it would be nice if this could be configured like:

```yaml
      "Bing": {
          "description": "Aerial Imagery",
          "type": "bingmap",
          "zoom_level": 12
      }
```
