### ISSUE TITLE
Exception: Mask format 'png' does not allow 'binary' encoding! Allowed are: integer,rgb,rgba

### ISSUE THREAD

**Issue by robmarkcole** [ESA-PhiLab/iris#51]
I want to annotate change detection and generate 8 bit`mask.png` which is single channel and 0 is `no-change` and 255 is `change`, which I think is pretty standard format. However the config below:

```yaml
    "segmentation": {
        "path": "{id}/mask.png",
        "mask_encoding": "binary",
        "score": "f1",
        "mask_area": [0, 0, 256, 256],
        "unverified_threshold": 1,
        "test_images": null
    },
```

Returns
```
Exception: Mask format 'png' does not allow 'binary' encoding! Allowed are: integer,rgb,rgba
```
